import { ClerkProvider } from '@clerk/nextjs';

import type { Metadata } from 'next';
import localFont from 'next/font/local';
import './globals.css';
import { ThemeProvider } from '@/components/theme-provider';

const myFontRegular = localFont({
	src: './fonts/BeVietnamPro-Regular.ttf',
	weight: '400 ',
	variable: '--font-myFont-regular',
});

export const metadata: Metadata = {
	title: 'STDEV BLOG APP',
	description: 'Generated by STDEV',
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<ClerkProvider>
			<html lang="en" suppressHydrationWarning>
				<body className={`${myFontRegular} antialiased`}>
					<ThemeProvider
						attribute="class"
						defaultTheme="system"
						enableSystem
						disableTransitionOnChange
					>
						{children}
					</ThemeProvider>
				</body>
			</html>
		</ClerkProvider>
	);
}
